version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    restart: unless-stopped
    ports:
      - 4000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 8081:80
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend: